name = "NBT"
uuid = "b6fc1ac1-9d30-4df3-aa0b-dd666eb91533"
authors = ["Ellie <intricatebread@gmail.com> and contributors"]
version = "1.0.0"

[deps]
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Aqua = "^0.8"
BufferedStreams = "^1.2"
CodecZlib = "^0.7"
LazyArtifacts = "^1.11"
OrderedCollections = "^1.8"
Test = "^1.11"
julia = "^1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "LazyArtifacts", "Test"]
